version: "3.9"

services:
  football_notifier:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - football_notifier.env
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=notifier_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword