from enum import Enum

import emoji


def get_emoji_text_by_name(name: str) -> str:
    return emoji.emojize(f":{name}:", language="alias")


class Emojis(Enum):
    FRANCE = emoji.emojize(":France:", language="alias")
    ARGENTINA = emoji.emojize(":Argentina:", language="alias")
    NETHERLANDS = emoji.emojize(":Netherlands:", language="alias")
    SPAIN = emoji.emojize(":Spain:", language="alias")
    GOAT = emoji.emojize(":goat:", language="alias")
    THOUGHT_BALLOON = emoji.emojize(":thought_balloon:", language="alias")
    WAVING_HAND = emoji.emojize(":wave:", language="alias")
    ALARM_CLOCK = emoji.emojize(":alarm_clock:", language="alias")
    EARTH = emoji.emojize(":globe_showing_Americas:", language="alias")
    SOCCER_BALL = emoji.emojize(":soccer:", language="alias")
    TROPHY = emoji.emojize(":trophy:", language="alias")
    PUSHPIN = emoji.emojize(":pushpin:", language="alias")
    SCALE = emoji.emojize(":balance_scale:", language="alias")
    GLOBE = emoji.emojize(":globe_with_meridians:", language="alias")
    EUROPEAN_UNION = emoji.emojize(":European_Union:", language="alias")
    SPIRAL_CALENDAR = emoji.emojize(":spiral_calendar:", language="alias")
    RED_EXCLAMATION_MARK = emoji.emojize(":red_exclamation_mark:", language="alias")
    RIGHT_ARROW = emoji.emojize(":right_arrow:", language="alias")
    CHART_INCREASING = emoji.emojize(":chart_increasing:", language="alias")
    CHECK_MARK = emoji.emojize(":check_mark:", language="alias")
    GOAL_NET = emoji.emojize(":goal_net:", language="alias")
    GLOBE_WITH_MERIDIANS = emoji.emojize(":globe_with_meridians:", language="alias")
    FILM_PROJECTOR = emoji.emojize(":film_projector:", language="alias")
    GLOVES = emoji.emojize(":gloves:", language="alias")
    JOYSTICK = emoji.emojize(":joystick:", language="alias")
    SHIELD = emoji.emojize(":shield:", language="alias")
    MAGIC_WAND = emoji.emojize(":magic_wand:", language="alias")
    SCORING = emoji.emojize(
        ":person_playing_handball_dark_skin_tone:", language="alias"
    )
    LIGHT_BULB = emoji.emojize(":light_bulb:", language="alias")
    SKULL = emoji.emojize(":skull:", language="alias")
    NUMBERS = emoji.emojize(":input_numbers:", language="alias")
    FAMILY = emoji.emojize(":input_numbers:", language="alias")
    FLEXED_BICEPS = emoji.emojize(":flexed_biceps:", language="alias")
    MICROBE = emoji.emojize(":microbe:", language="alias")
    FACE_WITH_MEDICAL_MASK = emoji.emojize(":face_with_medical_mask:", language="alias")
    TELEVISION = emoji.emojize(":television:", language="alias")
    BLUE_CIRCLE = emoji.emojize(":blue_circle:", language="alias")
    YELLOW_CIRCLE = emoji.emojize(":yellow_circle:", language="alias")
    PIRATE_FLAG = emoji.emojize(":pirate_flag:", language="alias")
    WHITE_CIRCLE = emoji.emojize(":white_circle:", language="alias")
    RED_CIRCLE = emoji.emojize(":red_circle:", language="alias")
    RIGHT_FACING_FIST = emoji.emojize(":right-facing_fist:", language="alias")
    LEFT_FACING_FIST = emoji.emojize(":left-facing_fist:", language="alias")
    SAD_FACE = emoji.emojize(":crying_face:", language="alias")
    STADIUM = emoji.emojize(":stadium:", language="alias")
    POLICE_WOMAN = emoji.emojize(":woman_police_officer:", language="alias")
    MAN_RUNNING = emoji.emojize(":man_running:", language="alias")
    CROSS_MARK = emoji.emojize(":cross_mark:", language="alias")
    PARTYING_FACE = emoji.emojize(":partying_face:", language="alias")
    NO_ENTRY = emoji.emojize(":no_entry:", language="alias")
    CHECK_MARK_BUTTON = emoji.emojize(":check_mark_button:", language="alias")
    BELL = emoji.emojize(":bell:", language="alias")
    SPEAKING_HEAD = emoji.emojize(":speaking_head:", language="alias")
    FOLDED_HANDS = emoji.emojize(":folded_hands:", language="alias")
    SMILEY_FACE = emoji.emojize(":beaming_face_with_smiling_eyes:", language="alias")
    ROBOT = emoji.emojize(":robot:", language="alias")
    DEVELOPER = emoji.emojize(":technologist_light_skin_tone:", language="alias")
    DOWN_FACING_FIST = emoji.emojize(":backhand_index_pointing_down:", language="alias")
    MINUS = emoji.emojize(":minus:", language="alias")
    EQUAL = emoji.emojize(":heavy_equals_sign:", language="alias")
    FACE_WITHOUT_MOUTH = emoji.emojize(":face_without_mouth:", language="alias")
    BACK_ARROW = emoji.emojize(":BACK_arrow:", language="alias")
    SOON_ARROW = emoji.emojize(":SOON_arrow:", language="alias")
